### ISSUE TITLE
按照文档执行报错

### ISSUE THREAD

**Issue by weifeng2** [livoras/nestscript#35]

**Comment by weifeng2** [comment]
拉去master分支，将/nsc/bin/run文件中的#!/usr/bin/env ts-node修改为#!/usr/bin/env node，然后在nestscript-master目录下执行npx nsc compile main.js main npx nsc run main，正常输出了，注意需要安装Oclif环境，参考http://semlinker.com/oclif-node-cli/，楼主的命令使用了oclif框架，本人逆向工作者，遇到了个网站使用了这个项目进行了JS加密，一摸一样，使用其他方式破解了，还是想学习下虚拟机解密二进制这块。

**Comment by livoras** [comment]
想了解一下是哪个网站

**Comment by weifeng2** [comment]
这个网站目前还原到以前的版本了，没有用虚拟机加载JS了，网站不方便透漏，实在不好意思。
